version: '3'

services:

  db:
    image: mysql:8.0.22
    container_name: uib
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: uib
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"

  flyway:
    image: flyway/flyway:7.0.1
    container_name: flyway
    command: -url=jdbc:mysql://localhost:3306/uib -user=root -password=P@ssw0rd -connectRetries=60 migrate
    network_mode: host
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db