name: build-and-test
on: [pull_request]
jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

      - name: Clean and build with dotnet
        working-directory: src/
        run: |
          dotnet clean
          dotnet build

      - name: Test Units with dotnet
        working-directory: tests/UiB.Unit.Tests
        run: dotnet test
  
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Clean install dependencies and build
        working-directory: src/UiB.UI
        run: |
          yarn install
          yarn build
